Vagrant.configure("2") do |config|

    config.vm.box_check_update = false
  
    # Web01 configuration
    config.vm.define "web01" do |web01|
      web01.vm.box = "ubuntu/focal64"
      web01.vm.hostname = "web01"
      web01.vm.network "private_network", ip: "192.168.56.14"
      
     
    end
  
    # Web02 configuration
    config.vm.define "web02" do |web02|
      web02.vm.box = "ubuntu/focal64"
      web02.vm.hostname = "web02.local"
      web02.vm.network "private_network", ip: "192.168.56.15"
     
    end
  
    # DB01 configuration
    config.vm.define "db01" do |db01|
      db01.vm.box = "centos/8"
      db01.vm.hostname = "db01.local"
      db01.vm.network "private_network", ip: "192.168.56.16"
     
    # Provisioning 
      db01.vm.provision "shell", inline: <<-SHELL
        yum install mariadb-server unzip -y
        systemctl start mariadb
      SHELL
    end
  end
  